Repository TUK-SPORTIFY/sportify-backend, pull requests merged in 2024-11, with the labels that each got.

#2 feat: SportVoucher 도메인 생성 및 공통응답 포맷 생성
  build.gradle
  src/main/java/com/tuk/sportify/global/advice/ErrorResponse.java
  src/main/java/com/tuk/sportify/global/advice/GlobalResponseBodyAdvice.java
  src/main/java/com/tuk/sportify/global/advice/SuccessResponse.java
  src/main/java/com/tuk/sportify/sportvoucher/domain/Course.java
  src/main/java/com/tuk/sportify/sportvoucher/domain/Facility.java
  src/main/java/com/tuk/sportify/sportvoucher/domain/Item.java
  src/main/java/com/tuk/sportify/sportvoucher/domain/SportVoucher.java
Labels: feat

#6 Feat/#5 user domain
  src/main/java/com/tuk/sportify/member/controller/MemberController.java
  src/main/java/com/tuk/sportify/member/domain/Member.java
  src/main/java/com/tuk/sportify/member/repository/MemberRepository.java
  src/main/java/com/tuk/sportify/member/service/MemberService.java
  src/test/java/com/tuk/sportify/member/service/MemberServiceTest.java
Labels: feat

#9 Feat/#7 crew
  build.gradle
  src/main/java/com/tuk/sportify/address/service/AddressConvertService.java
  src/main/java/com/tuk/sportify/address/util/RequestParamCreator.java
  src/main/java/com/tuk/sportify/crew/domain/Crew.java
  src/main/java/com/tuk/sportify/global/utils/StringFormatter.java
  src/main/java/com/tuk/sportify/sportvoucher/controller/SportVoucherController.java
  src/main/java/com/tuk/sportify/sportvoucher/domain/Course.java
  src/main/java/com/tuk/sportify/sportvoucher/domain/SportVoucher.java
  src/main/java/com/tuk/sportify/sportvoucher/repository/SportVoucherRepository.java
  src/main/java/com/tuk/sportify/sportvoucher/service/SportVoucherService.java
  src/main/java/com/tuk/sportify/vouchermember/controller/VoucherMemberController.java
  src/main/java/com/tuk/sportify/vouchermember/domain/VoucherMember.java
  src/main/java/com/tuk/sportify/vouchermember/dto/CrewVoucher.java
  src/main/java/com/tuk/sportify/vouchermember/dto/PersonalAndCrewVoucherResponse.java
  src/main/java/com/tuk/sportify/vouchermember/dto/PersonalVoucher.java
  src/main/java/com/tuk/sportify/vouchermember/repository/VoucherMemberRepository.java
  src/main/java/com/tuk/sportify/vouchermember/service/VoucherMemberService.java
  src/main/java/com/tuk/sportify/vouchermember/service/mapper/VoucherMemberMapper.java
Labels: feat

#12 fix: JPQL 쿼리 변경
  src/main/java/com/tuk/sportify/vouchermember/repository/VoucherMemberRepository.java
Labels: fix

#16 Feat/#15 voucher search
  src/main/java/com/tuk/sportify/crew/controller/CrewController.java
  src/main/java/com/tuk/sportify/global/argumentresolver/AuthenticationMember.java
  src/main/java/com/tuk/sportify/global/argumentresolver/AuthenticationMemberArgumentResolver.java
  src/main/java/com/tuk/sportify/global/config/HandlerResolverConfig.java
  src/main/java/com/tuk/sportify/global/response/ErrorResponse.java
  src/main/java/com/tuk/sportify/global/response/GlobalResponseBodyAdvice.java
  src/main/java/com/tuk/sportify/member/jwt/token/TokenProvider.java
  src/main/java/com/tuk/sportify/member/principle/UserPrinciple.java
  src/main/java/com/tuk/sportify/sportvoucher/controller/SportVoucherController.java
  src/main/java/com/tuk/sportify/sportvoucher/domain/Item.java
  src/main/java/com/tuk/sportify/sportvoucher/domain/MiddleCategory.java
  src/main/java/com/tuk/sportify/sportvoucher/domain/SportVoucher.java
  src/main/java/com/tuk/sportify/sportvoucher/dto/VoucherResponse.java
  src/main/java/com/tuk/sportify/sportvoucher/dto/VoucherSearchResponse.java
  src/main/java/com/tuk/sportify/sportvoucher/repository/SportVoucherRepository.java
  src/main/java/com/tuk/sportify/sportvoucher/service/SportVoucherService.java
  src/main/java/com/tuk/sportify/sportvoucher/service/mapper/SportVoucherMapper.java
  src/main/java/com/tuk/sportify/vouchermember/controller/VoucherMemberController.java
Labels: feat

#20 feat: 로그아웃 구현
  build.gradle
  src/main/java/com/tuk/sportify/member/controller/MemberController.java
  src/main/java/com/tuk/sportify/member/jwt/AccessTokenBlackList.java
  src/main/java/com/tuk/sportify/member/jwt/JwtConfig.java
  src/main/java/com/tuk/sportify/member/jwt/JwtFilter.java
  src/main/java/com/tuk/sportify/member/jwt/SecurityConfig.java
  src/main/java/com/tuk/sportify/member/jwt/token/TokenProvider.java
  src/main/java/com/tuk/sportify/member/principle/UserPrinciple.java
  src/main/java/com/tuk/sportify/member/redis/RedisConfig.java
  src/main/java/com/tuk/sportify/member/service/MemberService.java
  src/main/resources/application.yml
Labels: feat

#24 Feat/#23 address
  .github/workflows/sportify-cd.yml
  docker-compose.yml
  src/main/java/com/tuk/sportify/address/controller/AddressController.java
  src/main/java/com/tuk/sportify/address/domain/Address.java
  src/main/java/com/tuk/sportify/address/dto/AddressDto.java
  src/main/java/com/tuk/sportify/address/dto/AddressListResponse.java
  src/main/java/com/tuk/sportify/address/dto/AddressRegisterRequest.java
  src/main/java/com/tuk/sportify/address/dto/AddressRegisterResponse.java
  src/main/java/com/tuk/sportify/address/dto/AddressResponse.java
  src/main/java/com/tuk/sportify/address/dto/ChangedAddressResponse.java
  src/main/java/com/tuk/sportify/address/exception/AddressNotFoundException.java
  src/main/java/com/tuk/sportify/address/repository/AddressRepository.java
  src/main/java/com/tuk/sportify/address/service/AddressService.java
  src/main/java/com/tuk/sportify/address/service/mapper/AddressMapper.java
  src/main/java/com/tuk/sportify/crew/service/CrewService.java
  src/main/java/com/tuk/sportify/facade/service/CrewVoucherFacadeService.java
  src/main/java/com/tuk/sportify/facade/service/MemberAddressFacadeService.java
  src/main/java/com/tuk/sportify/global/status_code/ErrorCode.java
  src/main/java/com/tuk/sportify/member/controller/MemberController.java
  src/main/java/com/tuk/sportify/member/domain/Member.java
  src/main/java/com/tuk/sportify/member/dto/CreateMemberRequest.java
  src/main/java/com/tuk/sportify/member/dto/LoginMemberRequest.java
  src/main/java/com/tuk/sportify/member/dto/LoginResponse.java
  src/main/java/com/tuk/sportify/member/jwt/SecurityConfig.java
  src/main/java/com/tuk/sportify/member/repository/MemberRepository.java
  src/main/java/com/tuk/sportify/member/service/MemberService.java
  src/main/java/com/tuk/sportify/member/service/mapper/MemberMapper.java
  src/main/java/com/tuk/sportify/sportvoucher/controller/SportVoucherController.java
  src/main/java/com/tuk/sportify/sportvoucher/dto/VoucherSearchResponse.java
  src/main/java/com/tuk/sportify/sportvoucher/service/SportVoucherService.java
Labels: feat

#28 Feat/#26 sport voucher entity
  build.gradle
  geocoding/save_to_db_with_point.py
  src/main/java/com/tuk/sportify/address/domain/Address.java
  src/main/java/com/tuk/sportify/address/service/mapper/AddressMapper.java
  src/main/java/com/tuk/sportify/facade/service/MemberAddressFacadeService.java
  src/main/java/com/tuk/sportify/global/utils/GeometryConverter.java
  src/main/java/com/tuk/sportify/global/utils/SportifyDateFormatter.java
  src/main/java/com/tuk/sportify/global/utils/StringFormatter.java
  src/main/java/com/tuk/sportify/member/service/mapper/MemberMapper.java
  src/main/java/com/tuk/sportify/sportvoucher/controller/SportVoucherController.java
  src/main/java/com/tuk/sportify/sportvoucher/domain/Course.java
  src/main/java/com/tuk/sportify/sportvoucher/domain/Facility.java
  src/main/java/com/tuk/sportify/sportvoucher/domain/Item.java
  src/main/java/com/tuk/sportify/sportvoucher/domain/SportVoucher.java
  src/main/java/com/tuk/sportify/sportvoucher/dto/PopularVoucherResponse.java
  src/main/java/com/tuk/sportify/sportvoucher/dto/VoucherResponse.java
  src/main/java/com/tuk/sportify/sportvoucher/repository/SportVoucherRepository.java
  src/main/java/com/tuk/sportify/sportvoucher/service/SportVoucherService.java
  src/main/java/com/tuk/sportify/sportvoucher/service/mapper/SportVoucherMapper.java
Labels: feat

#34 refactor: 기본 주소지 반환
  dump.rdb
  src/main/java/com/tuk/sportify/address/domain/Address.java
  src/main/java/com/tuk/sportify/crew/controller/CrewController.java
  src/main/java/com/tuk/sportify/crew/domain/Crew.java
  src/main/java/com/tuk/sportify/crew/service/ImageService.java
  src/main/java/com/tuk/sportify/global/DefaultAddress.java
  src/main/java/com/tuk/sportify/global/utils/SportifyDateFormatter.java
  src/main/java/com/tuk/sportify/member/domain/Member.java
  src/main/java/com/tuk/sportify/sportvoucher/dto/VoucherResponse.java
  src/main/java/com/tuk/sportify/sportvoucher/service/SportVoucherConst.java
  src/main/java/com/tuk/sportify/sportvoucher/service/SportVoucherService.java
  src/main/java/com/tuk/sportify/sportvoucher/service/mapper/SportVoucherMapper.java
Labels: ⚙️Refactor

#36 Feat/#35 response field add
  src/main/java/com/tuk/sportify/crew/controller/CrewController.java
  src/main/java/com/tuk/sportify/crew/dto/CreateCrewRequest.java
  src/main/java/com/tuk/sportify/member/domain/Member.java
  src/main/java/com/tuk/sportify/sportvoucher/dto/VoucherDetailResponse.java
  src/main/java/com/tuk/sportify/sportvoucher/dto/VoucherResponse.java
  src/main/java/com/tuk/sportify/sportvoucher/service/mapper/SportVoucherMapper.java
Labels: ✨Feat, ⚙️Refactor
